version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sakto_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    networks:
      - sakto_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    container_name: sakto_frontend_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - sakto_network

  nginx:
    image: nginx:alpine
    container_name: sakto_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/docker-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
    environment:
      - DOCKER_ENV=local
    entrypoint: ["/usr/local/bin/custom-entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - sakto_network

networks:
  sakto_network:
    driver: bridge

volumes:
  dbdata: 