<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CBU Fund Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #2c3e50;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }
        .email-container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 30px;
            margin: 20px 0;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e9ecef;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
            font-size: 28px;
        }
        .header h2 {
            color: #3498db;
            margin: 10px 0 0;
            font-size: 22px;
        }
        .user-info {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 25px;
            font-size: 14px;
            color: #6c757d;
        }
        .section {
            margin-bottom: 35px;
        }
        .section-title {
            color: #2c3e50;
            border-bottom: 2px solid #e9ecef;
            padding-bottom: 10px;
            margin-bottom: 20px;
            font-size: 20px;
        }
        .stat-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 25px;
        }
        .stat-item {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #e9ecef;
            transition: transform 0.2s;
        }
        .stat-item:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .stat-label {
            font-weight: 600;
            color: #6c757d;
            margin-bottom: 8px;
            font-size: 14px;
        }
        .stat-value {
            font-size: 1.4em;
            color: #2c3e50;
            font-weight: 600;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
            background-color: #ffffff;
            border-radius: 8px;
            overflow: hidden;
        }
        th, td {
            padding: 15px;
            text-align: left;
            border-bottom: 1px solid #e9ecef;
        }
        th {
            background-color: #f8f9fa;
            font-weight: 600;
            color: #2c3e50;
        }
        tr:hover {
            background-color: #f8f9fa;
        }
        .message {
            background: #e3f2fd;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            font-style: italic;
            color: #1976d2;
            border-left: 4px solid #1976d2;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e9ecef;
            color: #6c757d;
            font-size: 0.9em;
        }
        .currency {
            font-weight: 600;
            color: #2c3e50;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <h1>CBU Fund Report</h1>
            <h2>{{ $fund['name'] }}</h2>
        </div>

        <div class="user-info">
            <p><strong>Generated by:</strong> {{ auth()->user()->name }}</p>
            <p><strong>Email:</strong> {{ auth()->user()->email }}</p>
        </div>

        @if(isset($message) && is_string($message) && !empty($message))
        <div class="message">
            {!! $message !!}
        </div>
        @endif

        <div class="section">
            <h3 class="section-title">Fund Overview</h3>
            <div class="stat-grid">
                <div class="stat-item">
                    <div class="stat-label">Current Balance</div>
                    <div class="stat-value">{{ $appCurrency->symbol }}{{ number_format($statistics['currentBalance'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</div>
                </div>
                <div class="stat-item">
                    <div class="stat-label">Number of Shares</div>
                    <div class="stat-value">{{ $statistics['numberOfShares'] }}</div>
                </div>
                <div class="stat-item">
                    <div class="stat-label">Value Per Share</div>
                    <div class="stat-value">{{ $appCurrency->symbol }}{{ number_format($statistics['valuePerShare'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</div>
                </div>
                <div class="stat-item">
                    <div class="stat-label">Target Amount</div>
                    <div class="stat-value">{{ $appCurrency->symbol }}{{ number_format($fund['target_amount'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</div>
                </div>
            </div>
        </div>

        <div class="section">
            <h3 class="section-title">Recent Contributions</h3>
            @if(count($recentContributions) > 0)
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>Notes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($recentContributions as $contribution)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($contribution['contribution_date'])->format('F j, Y') }}</td>
                        <td>{{ $appCurrency->symbol }}{{ number_format($contribution['amount'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</td>
                        <td>{{ $contribution['notes'] ?? '-' }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <p>No recent contributions</p>
            @endif
        </div>

        <div class="section">
            <h3 class="section-title">Recent Withdrawals</h3>
            @if(count($recentWithdrawals) > 0)
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>Notes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($recentWithdrawals as $withdrawal)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($withdrawal['date'])->format('F j, Y') }}</td>
                        <td>{{ $appCurrency->symbol }}{{ number_format($withdrawal['amount'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</td>
                        <td>{{ $withdrawal['notes'] ?? '-' }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <p>No recent withdrawals</p>
            @endif
        </div>

        <div class="section">
            <h3 class="section-title">Recent Dividends</h3>
            @if(count($recentDividends) > 0)
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>Notes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($recentDividends as $dividend)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($dividend['dividend_date'])->format('F j, Y') }}</td>
                        <td>{{ $appCurrency->symbol }}{{ number_format($dividend['amount'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</td>
                        <td>{{ $dividend['notes'] ?? '-' }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <p>No recent dividends</p>
            @endif
        </div>

        <div class="section">
            <h3 class="section-title">Fund Statistics</h3>
            <div class="stat-grid">
                <div class="stat-item">
                    <div class="stat-label">Total Contributions</div>
                    <div class="stat-value">{{ $appCurrency->symbol }}{{ number_format($statistics['totalContributions'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</div>
                </div>
                <div class="stat-item">
                    <div class="stat-label">Total Withdrawals</div>
                    <div class="stat-value">{{ $appCurrency->symbol }}{{ number_format($statistics['totalWithdrawals'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</div>
                </div>
                <div class="stat-item">
                    <div class="stat-label">Total Dividends</div>
                    <div class="stat-value">{{ $appCurrency->symbol }}{{ number_format($statistics['totalDividends'], 2, $appCurrency->decimal_separator, $appCurrency->thousands_separator) }}</div>
                </div>
            </div>
        </div>

        <div class="footer">
            <p>This is an automated report. Please do not reply to this email.</p>
            <p>Generated on {{ now()->format('F j, Y H:i:s') }}</p>
        </div>
    </div>
</body>
</html> 