export { PatientTable } from './PatientTable';
export { AddPatientForm } from './AddPatientForm';
export { HistoryDialog } from './HistoryDialog';
export { DentalChartDialog } from './DentalChartDialog';
export { EditPatientDialog } from './EditPatientDialog';
export { DeleteConfirmationDialog } from './DeleteConfirmationDialog';
export { AddCheckupDialog } from './AddCheckupDialog';
export { default as AppointmentTable } from './AppointmentTable';
export { default as AddAppointmentDialog } from './AddAppointmentDialog';
export { default as EditAppointmentDialog } from './EditAppointmentDialog';
